markdown: rdiscount
pygments: true
auto: true
rdiscount:
  extensions: [smart]
title : RoboZombie
production_url : http://sahan.me/RoboZombie
description: Effortless Android Networking
author :
  name : Sahan Jayasinghe
  github : sahan
  email: sahan@lonepulse.com
